CREATE TABLE CITIES(NAME VARCHAR(30));

INSERT INTO CITIES(NAME) VALUES('Bratislava');
INSERT INTO CITIES(NAME) VALUES('Budapest');
INSERT INTO CITIES(NAME) VALUES('Prague');
INSERT INTO CITIES(NAME) VALUES('Warsaw');
INSERT INTO CITIES(NAME) VALUES('Los Angeles');
INSERT INTO CITIES(NAME) VALUES('New York');
INSERT INTO CITIES(NAME) VALUES('Edinburgh');
INSERT INTO CITIES(NAME) VALUES('Berlin');